### ISSUE TITLE
FLIMfit will not load a .omeTIFF file from a Leica DMi8

### ISSUE THREAD

**Issue by kdbuchan1** [openmicroscopy/Imperial-FLIMfit#386]
Hi there,

I'm having trouble importing a .ometiff file from a Leica DMi8 microscope. I also tried opening in a picoquant file but I can't seem to fit the IRF decay properly. The IRF never seems to be implemented properly.

If you can get back to me that would be amazing. I'm trying to finish off a publication and I only have a few weeks to get it together.

Thank you!
Kyle
----

Error using flim_data_series/get_image_dimensions (line 185)
Java exception occurred: 
java.lang.IndexOutOfBoundsException: Index: 1, Size: 1
	at java.util.ArrayList.rangeCheck(Unknown Source)
	at java.util.ArrayList.get(Unknown Source)
	at ome.xml.model.Pixels.getChannel(Pixels.java:628)
	at ome.xml.meta.OMEXMLMetadataImpl.getChannelName(OMEXMLMetadataImpl.java:1211)

Error in flim_data_series/load_multiple (line 30)

Error in flim_data_series/load_single (line 104)

Error in flim_data_series_controller/load_single (line 168)

Error in front_end_menu_controller/menu_file_load_single_callback (line 656)

Error in front_end_menu_controller>@(varargin)obj.menu_file_load_single_callback(varargin{:})

Error in EC (line 7)

Error in front_end_menu_controller>@(x,y)EC(fcn) (line 263)

**Comment by seanwarren** [comment]
Hi Kyle,

From a Leica SP8 you need to export your data as a PT3 file for analysis in FLIMfit. An OME TIFF from the Leica software does not contain the time resolved data.
